# Generated by Django 3.2.6 on 2021-08-17 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_date_art_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('show', models.CharField(choices=[('S', 'Somnyama Ngonyama'), ('W', 'WoA! Pt.2'), ('P', 'Paradigm of Charcoal')], default='S', max_length=1)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.art')),
            ],
        ),
    ]
