# Generated by Django 3.2.6 on 2021-08-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_exhibition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bid', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='exhibition',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='date',
            field=models.DateField(verbose_name='exhibition date'),
        ),
        migrations.AddField(
            model_name='art',
            name='buyers',
            field=models.ManyToManyField(to='main_app.Buyer'),
        ),
    ]
